### ISSUE TITLE
Add E2E Automation for Rancher Monitoring Sample Watchdog Alert

### ISSUE THREAD

**Issue by deepakpunia-suse** [rancher/observability-e2e#4]
### Description:
Implement end-to-end tests to verify the Rancher monitoring sample watchdog alert functionality. 

### Tasks:
- [ ] Create new E2E files to add tests.
- [ ] Add the first E2E test to verify the watchdog alert.
- [ ] Successfully execute the test after installation.

### Expected Outcome:
The script should successfully validate that the sample watchdog alert is active.
